<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EvaluationHarness</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../contracts/ServiceContract/src/ServiceContract.csproj" />
    <ProjectReference Include="../../../contracts/ServiceConfiguration/src/ServiceConfiguration.csproj" />
  </ItemGroup>

</Project>
