<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ProcessingService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../contracts/ServiceContract/src/ServiceContract.csproj" />
    <ProjectReference Include="../../../contracts/ServiceConfiguration/src/ServiceConfiguration.csproj" />
    <ProjectReference Include="../../../ingestion/IngestionService/src/IngestionService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
  </ItemGroup>

</Project>
